version: '3.4'

services:
  exceletech.api:
    image: ${DOCKER_REGISTRY-}exceletechapi
    container_name: exceletech.api
    build:
      context: .
      dockerfile: ExceleTech.API/Dockerfile
    ports:
      - "5001:5001" 
    depends_on:
        - exceletech.database
  exceletech.database:
    image: postgres:latest
    container_name: exceletech.database
    environment:
        - POSTGRES_DB=ExceleTech
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
       - ./.containers/exceletech-db:/var/lib/postgresql/data
    ports:
        - 5432:5432
  exceletech.cache:
    image: redis:latest
    container_name: exceletech.cache
    restart: always
    ports:
      - '6379:6379'


